# Generated by Django 3.0.8 on 2020-08-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200801_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='author',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_file',
        ),
    ]
